In [104]:
#%pip install spacy

In [105]:
import numpy as np
import pandas as pd
import spacy

In [106]:
df = pd.read_excel('Final Data File_Training.xlsx',sheet_name=1)

In [107]:
df.head()

,Unique ID,Start Date,End Date,Q1. What is your current age? \n(Age),Q2. What is your gender? \n(Gender),Q3. Which of the following best describes the area or community in which you live? \n(Urban/Rural),Q4. Please indicate the answer that includes your entire household income in (previous year) before taxes. \n(Income),Q6 Which of the following types of alcoholic beverages have you consumed in the past 4 weeks?\n(Alcohol Category),Unnamed: 8,Unnamed: 9,...,Q13. How does the price fit with what you’d expect the shown to cost?\n(Concept_Price),Q14. Which statement below best describes how likely you would be to buy shown product if it were available at your local stores?\n(Concept_Purchase Intent),"Q15. If the shwon product was available to you, how often would you expect yourself to drink at least one of these products?\n(Concept_Drinking Frequency)",Q16A. What is the most important thing you LIKE about the shown concept}? This can include anything you would want kept for sure or aspects that might drive you to buy or try it… Please type a detailed response in the space below,"Q16B. What is the most important thing you DISLIKE about the shown concept}? This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you... Please type a detailed response in the space below.","Q17. We would like to know what effect this new product might have on the other beverages you buy. If it were available, would the shown product…? \n(Concept_Replacement Product)",Q18_1 What specific product that you are currently using would the shown product replace?\n Please type in ONE specific brand or product per space provided.,Q18_2 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.,Q18_3 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.,OE_Quality_Flag
0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,Beer,Flavored/Mixed Beer,Non-Alcoholic Beers,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,2024-10-11 09:43:37,2024-10-11 09:53:40,60.0,2.0,3.0,12.0,1,0,0,...,3.0,2.0,2.0,the packaging,nothing,1.0,NaN,NaN,NaN,0.0
2,5.0,2024-10-11 09:42:41,2024-10-11 09:55:49,61.0,1.0,3.0,3.0,1,0,0,...,3.0,5.0,4.0,It's a good and trusted brand.,It's seem some what generic.,2.0,Heineken,Miller Lite,Budwieser,0.0
3,6.0,2024-10-11 09:46:20,2024-10-11 09:56:42,58.0,1.0,1.0,8.0,1,0,0,...,3.0,1.0,0.0,Just that it is a lager beer,I don't like Anheiser Busch and their values a...,1.0,NaN,NaN,NaN,0.0
4,8.0,2024-10-11 09:47:15,2024-10-11 09:57:19,55.0,1.0,3.0,11.0,1,0,0,...,3.0,5.0,7.0,has a less filling effect,no dislike,2.0,michelob ultra,Miller light,corona,0.0

In [108]:
df.columns

Index(['Unique ID', 'Start Date', 'End Date',
       'Q1. What is your current age? \n(Age)',
       'Q2. What is your gender? \n(Gender)',
       'Q3. Which of the following best describes the area or community in which you live? \n(Urban/Rural)',
       'Q4.  Please indicate the answer that includes your entire household income in (previous year) before taxes. \n(Income)',
       'Q6 Which of the following types of alcoholic beverages have you consumed in the past 4 weeks?\n(Alcohol Category)',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14',
       'Q7. Which of the following beer types of have you consumed in the past 4 weeks? \n(Beer Category )',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21',
       'Q9. How relevant would you say the shown product is to you based on what you saw and read?\n(Concept Relevance)',
       'Q10. How appealing or unappealing is the shown product  to you?\n(Concept Appeal)',
       'Q11. How different do you think the shown product is from other beers currently available for purchase?\n(Concept Differentiation)',
       'Q12. Thinking about the shown product, which option describes how believable or unbelievable you feel the description and statements made about it are?\n(Concept Beleivability)',
       'Q13. How does the price fit with what you’d expect the shown to cost?\n(Concept_Price)',
       'Q14. Which statement below best describes how likely you would be to buy shown product if it were available at your local stores?\n(Concept_Purchase Intent)',
       'Q15. If the shwon product was available to you, how often would you expect yourself to drink at least one of these products?\n(Concept_Drinking Frequency)',
       'Q16A. What is the most important thing you LIKE about the shown concept}?     This can include anything you would want kept for sure or aspects that might drive you to buy or try it…       Please type a detailed response in the space below',
       'Q16B. What is the most important thing you DISLIKE about the shown concept}?    This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you...     Please type a detailed response in the space below.',
       'Q17. We would like to know what effect this new product might have on the other beverages you buy. If it were available, would the shown product…? \n(Concept_Replacement Product)',
       'Q18_1 What specific product that you are currently using would the shown product replace?\n Please type in ONE specific brand or product per space provided.',
       'Q18_2 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.',
       'Q18_3 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.',
       'OE_Quality_Flag'],
      dtype='object')

In [109]:
d = {}
cols = df.columns

for i in range(len(cols)):
    if cols[i].startswith("Unnamed"): 
        d[cols[i]] = df.iloc[0, i]  
d

{'Unnamed: 8': ' Flavored/Mixed Beer',
 'Unnamed: 9': ' Non-Alcoholic Beers',
 'Unnamed: 10': ' Hard Ciders',
 'Unnamed: 11': ' Hard Kombucha',
 'Unnamed: 12': ' Wine',
 'Unnamed: 13': ' Hard Beverage',
 'Unnamed: 14': ' Distilled Spirits',
 'Unnamed: 16': 'Domestic Regular Beer',
 'Unnamed: 17': 'Low Calorie Carb Beer',
 'Unnamed: 18': 'Domestic Craft',
 'Unnamed: 19': 'Imported Mexican Beer',
 'Unnamed: 20': 'Other Imported Beer',
 'Unnamed: 21': 'Non-Alcoholic Beer'}

In [110]:
df = df.rename(columns = d)
df.drop([0],axis=0,inplace=True)
df.head()

,Unique ID,Start Date,End Date,Q1. What is your current age? \n(Age),Q2. What is your gender? \n(Gender),Q3. Which of the following best describes the area or community in which you live? \n(Urban/Rural),Q4. Please indicate the answer that includes your entire household income in (previous year) before taxes. \n(Income),Q6 Which of the following types of alcoholic beverages have you consumed in the past 4 weeks?\n(Alcohol Category),Flavored/Mixed Beer,Non-Alcoholic Beers,...,Q13. How does the price fit with what you’d expect the shown to cost?\n(Concept_Price),Q14. Which statement below best describes how likely you would be to buy shown product if it were available at your local stores?\n(Concept_Purchase Intent),"Q15. If the shwon product was available to you, how often would you expect yourself to drink at least one of these products?\n(Concept_Drinking Frequency)",Q16A. What is the most important thing you LIKE about the shown concept}? This can include anything you would want kept for sure or aspects that might drive you to buy or try it… Please type a detailed response in the space below,"Q16B. What is the most important thing you DISLIKE about the shown concept}? This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you... Please type a detailed response in the space below.","Q17. We would like to know what effect this new product might have on the other beverages you buy. If it were available, would the shown product…? \n(Concept_Replacement Product)",Q18_1 What specific product that you are currently using would the shown product replace?\n Please type in ONE specific brand or product per space provided.,Q18_2 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.,Q18_3 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.,OE_Quality_Flag
1,3.0,2024-10-11 09:43:37,2024-10-11 09:53:40,60.0,2.0,3.0,12.0,1,0,0,...,3.0,2.0,2.0,the packaging,nothing,1.0,NaN,NaN,NaN,0.0
2,5.0,2024-10-11 09:42:41,2024-10-11 09:55:49,61.0,1.0,3.0,3.0,1,0,0,...,3.0,5.0,4.0,It's a good and trusted brand.,It's seem some what generic.,2.0,Heineken,Miller Lite,Budwieser,0.0
3,6.0,2024-10-11 09:46:20,2024-10-11 09:56:42,58.0,1.0,1.0,8.0,1,0,0,...,3.0,1.0,0.0,Just that it is a lager beer,I don't like Anheiser Busch and their values a...,1.0,NaN,NaN,NaN,0.0
4,8.0,2024-10-11 09:47:15,2024-10-11 09:57:19,55.0,1.0,3.0,11.0,1,0,0,...,3.0,5.0,7.0,has a less filling effect,no dislike,2.0,michelob ultra,Miller light,corona,0.0
5,10.0,2024-10-11 09:45:24,2024-10-11 09:57:30,64.0,1.0,5.0,3.0,1,1,0,...,5.0,5.0,6.0,Everything,Nothing,3.0,Coors light,Bud,Coors,0.0

In [111]:
d = {}
for i in range(len(cols)):
    if cols[i].startswith("Q"): 
        d[cols[i]] = cols[i][0:cols[i].index(' ')]
d

{'Q1. What is your current age? \n(Age)': 'Q1.',
 'Q2. What is your gender? \n(Gender)': 'Q2.',
 'Q3. Which of the following best describes the area or community in which you live? \n(Urban/Rural)': 'Q3.',
 'Q4.  Please indicate the answer that includes your entire household income in (previous year) before taxes. \n(Income)': 'Q4.',
 'Q6 Which of the following types of alcoholic beverages have you consumed in the past 4 weeks?\n(Alcohol Category)': 'Q6',
 'Q7. Which of the following beer types of have you consumed in the past 4 weeks? \n(Beer Category )': 'Q7.',
 'Q9. How relevant would you say the shown product is to you based on what you saw and read?\n(Concept Relevance)': 'Q9.',
 'Q10. How appealing or unappealing is the shown product  to you?\n(Concept Appeal)': 'Q10.',
 'Q11. How different do you think the shown product is from other beers currently available for purchase?\n(Concept Differentiation)': 'Q11.',
 'Q12. Thinking about the shown product, which option describes how believable or unbelievable you feel the description and statements made about it are?\n(Concept Beleivability)': 'Q12.',
 'Q13. How does the price fit with what you’d expect the shown to cost?\n(Concept_Price)': 'Q13.',
 'Q14. Which statement below best describes how likely you would be to buy shown product if it were available at your local stores?\n(Concept_Purchase Intent)': 'Q14.',
 'Q15. If the shwon product was available to you, how often would you expect yourself to drink at least one of these products?\n(Concept_Drinking Frequency)': 'Q15.',
 'Q16A. What is the most important thing you LIKE about the shown concept}?     This can include anything you would want kept for sure or aspects that might drive you to buy or try it…       Please type a detailed response in the space below': 'Q16A.',
 'Q16B. What is the most important thing you DISLIKE about the shown concept}?    This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you...     Please type a detailed response in the space below.': 'Q16B.',
 'Q17. We would like to know what effect this new product might have on the other beverages you buy. If it were available, would the shown product…? \n(Concept_Replacement Product)': 'Q17.',
 'Q18_1 What specific product that you are currently using would the shown product replace?\n Please type in ONE specific brand or product per space provided.': 'Q18_1',
 'Q18_2 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.': 'Q18_2',
 'Q18_3 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.': 'Q18_3'}

In [112]:
df = df.rename(columns = d)
#df.drop(df.columns[36],axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2299 entries, 1 to 2299
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unique ID              2299 non-null   float64
 1   Start Date             2299 non-null   datetime64[ns]
 2   End Date               2299 non-null   datetime64[ns]
 3   Q1.                    2299 non-null   float64
 4   Q2.                    2299 non-null   float64
 5   Q3.                    2299 non-null   float64
 6   Q4.                    2299 non-null   float64
 7   Q6                     2299 non-null   object
 8    Flavored/Mixed Beer   2299 non-null   object
 9    Non-Alcoholic Beers   2299 non-null   object
 10   Hard Ciders           2299 non-null   object
 11   Hard Kombucha         2299 non-null   object
 12   Wine                  2299 non-null   object
 13   Hard Beverage         2299 non-null   object
 14   Distilled Spirits     2299 non-null   object
 15  Q7.                    2299 non-null   object
 16  Domestic Regular Beer  2299 non-null   object
 17  Low Calorie Carb Beer  2299 non-null   object
 18  Domestic Craft         2299 non-null   object
 19  Imported Mexican Beer  2299 non-null   object
 20  Other Imported Beer    2299 non-null   object
 21  Non-Alcoholic Beer     2299 non-null   object
 22  Q9.                    2299 non-null   float64
 23  Q10.                   2299 non-null   float64
 24  Q11.                   2299 non-null   float64
 25  Q12.                   2299 non-null   float64
 26  Q13.                   2299 non-null   float64
 27  Q14.                   2299 non-null   float64
 28  Q15.                   2299 non-null   float64
 29  Q16A.                  2280 non-null   object
 30  Q16B.                  2228 non-null   object
 31  Q17.                   2299 non-null   float64
 32  Q18_1                  1257 non-null   object
 33  Q18_2                  1226 non-null   object
 34  Q18_3                  1216 non-null   object
 35  OE_Quality_Flag        2299 non-null   float64
dtypes: datetime64[ns](2), float64(14), object(20)
memory usage: 646.7+ KB

In [113]:
print(df["Start Date"].dt.day.value_counts())
print(df["Start Date"].dt.month.value_counts())
print(df["Start Date"].dt.year.value_counts())

Start Date
22    478
24    355
21    303
23    238
17    196
13    159
12    138
16     96
18     83
14     67
19     57
20     46
11     45
15     38
Name: count, dtype: int64
Start Date
10    2299
Name: count, dtype: int64
Start Date
2024    2299
Name: count, dtype: int64

In [114]:
print(df["End Date"].dt.day.value_counts())
print(df["End Date"].dt.month.value_counts())
print(df["End Date"].dt.year.value_counts())

End Date
22    487
24    356
21    293
23    238
17    193
13    159
12    135
16     95
18     87
14     69
19     57
20     46
11     45
15     39
Name: count, dtype: int64
End Date
10    2299
Name: count, dtype: int64
End Date
2024    2299
Name: count, dtype: int64

In [115]:
df['time_taken'] = (df['End Date'] - df['Start Date']).dt.total_seconds()

df.insert(3, 'time_taken', df.pop('time_taken'))
df.head()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q6,Flavored/Mixed Beer,...,Q13.,Q14.,Q15.,Q16A.,Q16B.,Q17.,Q18_1,Q18_2,Q18_3,OE_Quality_Flag
1,3.0,2024-10-11 09:43:37,2024-10-11 09:53:40,603.0,60.0,2.0,3.0,12.0,1,0,...,3.0,2.0,2.0,the packaging,nothing,1.0,NaN,NaN,NaN,0.0
2,5.0,2024-10-11 09:42:41,2024-10-11 09:55:49,788.0,61.0,1.0,3.0,3.0,1,0,...,3.0,5.0,4.0,It's a good and trusted brand.,It's seem some what generic.,2.0,Heineken,Miller Lite,Budwieser,0.0
3,6.0,2024-10-11 09:46:20,2024-10-11 09:56:42,622.0,58.0,1.0,1.0,8.0,1,0,...,3.0,1.0,0.0,Just that it is a lager beer,I don't like Anheiser Busch and their values a...,1.0,NaN,NaN,NaN,0.0
4,8.0,2024-10-11 09:47:15,2024-10-11 09:57:19,604.0,55.0,1.0,3.0,11.0,1,0,...,3.0,5.0,7.0,has a less filling effect,no dislike,2.0,michelob ultra,Miller light,corona,0.0
5,10.0,2024-10-11 09:45:24,2024-10-11 09:57:30,726.0,64.0,1.0,5.0,3.0,1,1,...,5.0,5.0,6.0,Everything,Nothing,3.0,Coors light,Bud,Coors,0.0

In [116]:
oe_df = pd.DataFrame()
oe_df['likes'] = df['Q16A.']
oe_df['dislikes'] = df['Q16B.']
oe_df.head()

,likes,dislikes
1,the packaging,nothing
2,It's a good and trusted brand.,It's seem some what generic.
3,Just that it is a lager beer,I don't like Anheiser Busch and their values a...
4,has a less filling effect,no dislike
5,Everything,Nothing

In [117]:
#%pip install better_profanity

In [118]:
import re
import spacy
from better_profanity import profanity

In [119]:
# Load Spacy model for language verification
nlp = spacy.load("en_core_web_sm")

def clean_text(text):
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)  # Remove special characters
    text = text.lower().strip()  # Convert to lowercase and strip spaces
    return text

def detect_profanity(text):
    return profanity.contains_profanity(text)

def verify_language(text):
    doc = nlp(text)
    return doc.lang_ == "en"  # Check if English
"""
def preprocess_text(text):
    text = clean_text(text)
    is_profanity = detect_profanity(text)
    is_english = verify_language(text)
    
    return {"cleaned_text": text, "contains_profanity": is_profanity, "is_english": is_english}"
"""

'\ndef preprocess_text(text):\n    text = clean_text(text)\n    is_profanity = detect_profanity(text)\n    is_english = verify_language(text)\n    \n    return {"cleaned_text": text, "contains_profanity": is_profanity, "is_english": is_english}"\n'

In [120]:
from sklearn.feature_extraction.text import CountVectorizer
from datetime import datetime
from scipy.spatial.distance import cosine

In [121]:
def calculate_entropy(text):
    if not isinstance(text, str) or len(text.strip()) == 0:
        return 0  # Return low entropy for empty text
    vectorizer = CountVectorizer()
    try:
        X = vectorizer.fit_transform([text])
    except ValueError:  # Catch empty vocabulary error
        return 0  
    probs = np.array(X.toarray()[0], dtype=np.float32)
    if np.sum(probs) == 0:
        return 0  # Avoid division by zero
    probs = probs / np.sum(probs)
    entropy = -np.sum(probs * np.log2(probs))
    return entropy


def is_gibberish(text, threshold=3.5):
    return calculate_entropy(text) < threshold

# Copy-paste detection using cosine similarity
def detect_copy_paste(response, all_responses, threshold=0.9):
    vectorizer = CountVectorizer().fit_transform([response] + all_responses)
    vectors = vectorizer.toarray()
    
    similarities = [1 - cosine(vectors[0], v) for v in vectors[1:]]
    return any(sim >= threshold for sim in similarities)

# Timestamp anomaly detection
def is_timestamp_anomalous(start_time, end_time, threshold=5):
    time_taken = (end_time - start_time).total_seconds()
    return time_taken < threshold

In [122]:
#%pip install sentence_transformers

In [123]:

from sentence_transformers import SentenceTransformer, util

model1 = SentenceTransformer("all-MiniLM-L6-v2")  # Lightweight model for semantic similarity

def check_relevance(response, expected_context):
    response_embedding = model1.encode(response, convert_to_tensor=True)
    context_embedding = model1.encode(expected_context, convert_to_tensor=True)
    
    similarity = util.pytorch_cos_sim(response_embedding, context_embedding).item()
    return similarity > 0.5  # Threshold for relevance"

In [124]:
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch
# Load GPT-2 model and tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

def detect_ai_generated(text):
    # Handle empty or whitespace-only text
    if not isinstance(text, str) or text.strip() == "":
        return False  # Assume non-AI for empty input
    
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

    # Ensure input_ids is not empty
    if inputs["input_ids"].size(1) == 0:
        return False  # Cannot determine AI generation for empty inputs
    
    with torch.no_grad():  # No need for gradients
        outputs = model(**inputs, labels=inputs["input_ids"])

    loss = outputs.loss.item()  # Log probability loss
    return loss  # AI-generated text tends to have lower loss values

In [125]:
df['Q16A.'] = df['Q16A.'].fillna("")
df['Q16B.'] = df['Q16B.'].fillna("")

df['Q16A.'] = df['Q16A.'].apply(lambda x: clean_text(x))
df['Q16B.'] = df['Q16B.'].apply(lambda x: clean_text(x))

df['profanity_16A'] = df['Q16A.'].apply(lambda x: detect_profanity(x))
df['profanity_16B'] = df['Q16B.'].apply(lambda x: detect_profanity(x))

df['relevance_16A'] = df['Q16A.'].apply(lambda x: check_relevance(x,"What is the most important thing you LIKE about the shown concept}?     This can include anything you would want kept for sure or aspects that might drive you to buy or try it"))
df['relevance_16B'] = df['Q16B.'].apply(lambda x: check_relevance(x,"What is the most important thing you DISLIKE about the shown concept}?    This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you"))

c:\Users\prana\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\bert\modeling_bert.py:440: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

In [126]:
df['language_16A'] = df['Q16A.'].apply(lambda x: verify_language(x))
df['language_16B'] = df['Q16B.'].apply(lambda x: verify_language(x))

df['entropy_16A'] = df['Q16A.'].apply(lambda x: calculate_entropy(x))
df['entropy_16B'] = df['Q16B.'].apply(lambda x: calculate_entropy(x))

In [127]:
df.head()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q6,Flavored/Mixed Beer,...,Q18_3,OE_Quality_Flag,profanity_16A,profanity_16B,relevance_16A,relevance_16B,language_16A,language_16B,entropy_16A,entropy_16B
1,3.0,2024-10-11 09:43:37,2024-10-11 09:53:40,603.0,60.0,2.0,3.0,12.0,1,0,...,NaN,0.0,False,False,False,False,True,True,1.000000,-0.000000
2,5.0,2024-10-11 09:42:41,2024-10-11 09:55:49,788.0,61.0,1.0,3.0,3.0,1,0,...,Budwieser,0.0,False,False,False,False,True,True,2.321928,2.321928
3,6.0,2024-10-11 09:46:20,2024-10-11 09:56:42,622.0,58.0,1.0,1.0,8.0,1,0,...,NaN,0.0,False,False,False,False,True,True,2.584963,3.392747
4,8.0,2024-10-11 09:47:15,2024-10-11 09:57:19,604.0,55.0,1.0,3.0,11.0,1,0,...,corona,0.0,False,False,False,False,True,True,2.000000,1.000000
5,10.0,2024-10-11 09:45:24,2024-10-11 09:57:30,726.0,64.0,1.0,5.0,3.0,1,1,...,Coors,0.0,False,False,False,False,True,True,-0.000000,-0.000000

In [128]:
df.describe()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q9.,Q10.,Q11.,Q12.,Q13.,Q14.,Q15.,Q17.,OE_Quality_Flag,entropy_16A,entropy_16B
count,2299.000000,2299,2299,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000
mean,1613.574163,2024-10-20 02:58:01.239234560,2024-10-20 03:12:42.208351488,880.969117,44.641148,1.463680,2.434102,6.234885,3.561548,3.785994,3.504132,3.271422,3.391910,3.543715,4.911701,1.710309,0.078295,2.135510,1.561504
min,3.000000,2024-10-11 09:41:00,2024-10-11 09:51:02,193.000000,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,-0.000000
25%,830.500000,2024-10-17 06:48:41.500000,2024-10-17 07:07:12.500000,526.000000,35.000000,1.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000,0.000000,1.000000,-0.000000
50%,1603.000000,2024-10-21 20:58:39,2024-10-21 21:17:54,733.000000,44.000000,1.000000,3.000000,6.000000,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,6.000000,2.000000,0.000000,2.251629,1.584963
75%,2386.500000,2024-10-23 04:09:52,2024-10-23 04:21:58,1044.000000,55.000000,2.000000,3.000000,10.000000,5.000000,5.000000,4.000000,4.000000,4.000000,5.000000,7.000000,2.000000,0.000000,2.947703,2.584963
max,3219.000000,2024-10-24 18:46:23,2024-10-24 18:58:00,3579.000000,65.000000,5.000000,5.000000,12.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,8.000000,3.000000,1.000000,6.412652,6.219014
std,917.010277,NaN,NaN,543.895876,11.895267,0.522645,1.295162,3.565327,1.274378,1.163095,1.143855,0.709451,0.804115,1.321700,2.509952,0.716906,0.268694,1.142212,1.260888

In [129]:
df['ai_generated_16A'] = df['Q16A.'].apply(lambda x: detect_ai_generated(x))
df['ai_generated_16B'] = df['Q16B.'].apply(lambda x: detect_ai_generated(x))

In [130]:
df.head()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q6,Flavored/Mixed Beer,...,profanity_16A,profanity_16B,relevance_16A,relevance_16B,language_16A,language_16B,entropy_16A,entropy_16B,ai_generated_16A,ai_generated_16B
1,3.0,2024-10-11 09:43:37,2024-10-11 09:53:40,603.0,60.0,2.0,3.0,12.0,1,0,...,False,False,False,False,True,True,1.000000,-0.000000,11.076096,NaN
2,5.0,2024-10-11 09:42:41,2024-10-11 09:55:49,788.0,61.0,1.0,3.0,3.0,1,0,...,False,False,False,False,True,True,2.321928,2.321928,5.227074,8.553175
3,6.0,2024-10-11 09:46:20,2024-10-11 09:56:42,622.0,58.0,1.0,1.0,8.0,1,0,...,False,False,False,False,True,True,2.584963,3.392747,4.422742,6.161152
4,8.0,2024-10-11 09:47:15,2024-10-11 09:57:19,604.0,55.0,1.0,3.0,11.0,1,0,...,False,False,False,False,True,True,2.000000,1.000000,6.919522,11.932405
5,10.0,2024-10-11 09:45:24,2024-10-11 09:57:30,726.0,64.0,1.0,5.0,3.0,1,1,...,False,False,False,False,True,True,-0.000000,-0.000000,NaN,NaN

In [131]:
df.describe()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q9.,Q10.,Q11.,Q12.,Q13.,Q14.,Q15.,Q17.,OE_Quality_Flag,entropy_16A,entropy_16B
count,2299.000000,2299,2299,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000
mean,1613.574163,2024-10-20 02:58:01.239234560,2024-10-20 03:12:42.208351488,880.969117,44.641148,1.463680,2.434102,6.234885,3.561548,3.785994,3.504132,3.271422,3.391910,3.543715,4.911701,1.710309,0.078295,2.135510,1.561504
min,3.000000,2024-10-11 09:41:00,2024-10-11 09:51:02,193.000000,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,-0.000000
25%,830.500000,2024-10-17 06:48:41.500000,2024-10-17 07:07:12.500000,526.000000,35.000000,1.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000,0.000000,1.000000,-0.000000
50%,1603.000000,2024-10-21 20:58:39,2024-10-21 21:17:54,733.000000,44.000000,1.000000,3.000000,6.000000,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,6.000000,2.000000,0.000000,2.251629,1.584963
75%,2386.500000,2024-10-23 04:09:52,2024-10-23 04:21:58,1044.000000,55.000000,2.000000,3.000000,10.000000,5.000000,5.000000,4.000000,4.000000,4.000000,5.000000,7.000000,2.000000,0.000000,2.947703,2.584963
max,3219.000000,2024-10-24 18:46:23,2024-10-24 18:58:00,3579.000000,65.000000,5.000000,5.000000,12.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,8.000000,3.000000,1.000000,6.412652,6.219014
std,917.010277,NaN,NaN,543.895876,11.895267,0.522645,1.295162,3.565327,1.274378,1.163095,1.143855,0.709451,0.804115,1.321700,2.509952,0.716906,0.268694,1.142212,1.260888