In [3]:
#%pip install spacy

In [4]:
import numpy as np
import pandas as pd
import spacy

In [5]:
df = pd.read_excel('Sample Data for Hackathon.xlsx',sheet_name=1)

In [6]:
df.head()

,Unique ID,Start Date,End Date,Q1. What is your current age? \n(Age),Q2. What is your gender? \n(Gender),Q3. Which of the following best describes the area or community in which you live? \n(Urban/Rural),Q4. Please indicate the answer that includes your entire household income in (previous year) before taxes. \n(Income),Q6 Which of the following types of alcoholic beverages have you consumed in the past 4 weeks?\n(Alcohol Category),Unnamed: 8,Unnamed: 9,...,Q14. Which statement below best describes how likely you would be to buy shown product if it were available at your local stores?\n(Concept_Purchase Intent),"Q15. If the shwon product was available to you, how often would you expect yourself to drink at least one of these products?\n(Concept_Drinking Frequency)",Q16A. What is the most important thing you LIKE about the shown concept}? This can include anything you would want kept for sure or aspects that might drive you to buy or try it… Please type a detailed response in the space below,"Q16B. What is the most important thing you DISLIKE about the shown concept}? This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you... Please type a detailed response in the space below.","Q17. We would like to know what effect this new product might have on the other beverages you buy. If it were available, would the shown product…? \n(Concept_Replacement Product)",Q18_1 What specific product that you are currently using would the shown product replace?\n Please type in ONE specific brand or product per space provided.,Q18_2 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.,Q18_3 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.,OE_Quality_Flag,Unnamed: 36
0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,Beer,Flavored/Mixed Beer,Non-Alcoholic Beers,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,2024-10-11 09:41:31,2024-10-11 09:49:38,62.0,2.0,3.0,1.0,1,0,0,...,4.0,5.0,It's a classic brand.,Nothing specific to dislike.,1.0,NaN,NaN,NaN,0.0,NaN
2,2.0,2024-10-11 09:41:41,2024-10-11 09:50:42,35.0,1.0,1.0,12.0,1,1,1,...,5.0,7.0,Taste,The glass,1.0,NaN,NaN,NaN,0.0,NaN
3,9.0,2024-10-11 09:41:03,2024-10-11 09:57:26,62.0,1.0,3.0,4.0,1,0,0,...,3.0,7.0,Why?,Pure is a misnomer,1.0,NaN,NaN,NaN,1.0,NaN
4,22.0,2024-10-11 10:14:09,2024-10-11 10:22:43,64.0,1.0,1.0,11.0,1,0,0,...,3.0,4.0,I have a lot to say,Not really,2.0,NaN,Beer,Drink,1.0,NaN

In [7]:
df.columns

Index(['Unique ID', 'Start Date', 'End Date',
       'Q1. What is your current age? \n(Age)',
       'Q2. What is your gender? \n(Gender)',
       'Q3. Which of the following best describes the area or community in which you live? \n(Urban/Rural)',
       'Q4.  Please indicate the answer that includes your entire household income in (previous year) before taxes. \n(Income)',
       'Q6 Which of the following types of alcoholic beverages have you consumed in the past 4 weeks?\n(Alcohol Category)',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14',
       'Q7. Which of the following beer types of have you consumed in the past 4 weeks? \n(Beer Category )',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21',
       'Q9. How relevant would you say the shown product is to you based on what you saw and read?\n(Concept Relevance)',
       'Q10. How appealing or unappealing is the shown product  to you?\n(Concept Appeal)',
       'Q11. How different do you think the shown product is from other beers currently available for purchase?\n(Concept Differentiation)',
       'Q12. Thinking about the shown product, which option describes how believable or unbelievable you feel the description and statements made about it are?\n(Concept Beleivability)',
       'Q13. How does the price fit with what you’d expect the shown to cost?\n(Concept_Price)',
       'Q14. Which statement below best describes how likely you would be to buy shown product if it were available at your local stores?\n(Concept_Purchase Intent)',
       'Q15. If the shwon product was available to you, how often would you expect yourself to drink at least one of these products?\n(Concept_Drinking Frequency)',
       'Q16A. What is the most important thing you LIKE about the shown concept}?     This can include anything you would want kept for sure or aspects that might drive you to buy or try it…       Please type a detailed response in the space below',
       'Q16B. What is the most important thing you DISLIKE about the shown concept}?    This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you...     Please type a detailed response in the space below.',
       'Q17. We would like to know what effect this new product might have on the other beverages you buy. If it were available, would the shown product…? \n(Concept_Replacement Product)',
       'Q18_1 What specific product that you are currently using would the shown product replace?\n Please type in ONE specific brand or product per space provided.',
       'Q18_2 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.',
       'Q18_3 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.',
       'OE_Quality_Flag', 'Unnamed: 36'],
      dtype='object')

In [8]:
d = {}
cols = df.columns

for i in range(len(cols)):
    if cols[i].startswith("Unnamed"): 
        d[cols[i]] = df.iloc[0, i]  
d

{'Unnamed: 8': ' Flavored/Mixed Beer',
 'Unnamed: 9': ' Non-Alcoholic Beers',
 'Unnamed: 10': ' Hard Ciders',
 'Unnamed: 11': ' Hard Kombucha',
 'Unnamed: 12': ' Wine',
 'Unnamed: 13': ' Hard Beverage',
 'Unnamed: 14': ' Distilled Spirits',
 'Unnamed: 16': 'Domestic Regular Beer',
 'Unnamed: 17': 'Low Calorie Carb Beer',
 'Unnamed: 18': 'Domestic Craft',
 'Unnamed: 19': 'Imported Mexican Beer',
 'Unnamed: 20': 'Other Imported Beer',
 'Unnamed: 21': 'Non-Alcoholic Beer',
 'Unnamed: 36': nan}

In [9]:
df = df.rename(columns = d)
df.drop([0],axis=0,inplace=True)
df.head()

,Unique ID,Start Date,End Date,Q1. What is your current age? \n(Age),Q2. What is your gender? \n(Gender),Q3. Which of the following best describes the area or community in which you live? \n(Urban/Rural),Q4. Please indicate the answer that includes your entire household income in (previous year) before taxes. \n(Income),Q6 Which of the following types of alcoholic beverages have you consumed in the past 4 weeks?\n(Alcohol Category),Flavored/Mixed Beer,Non-Alcoholic Beers,...,Q14. Which statement below best describes how likely you would be to buy shown product if it were available at your local stores?\n(Concept_Purchase Intent),"Q15. If the shwon product was available to you, how often would you expect yourself to drink at least one of these products?\n(Concept_Drinking Frequency)",Q16A. What is the most important thing you LIKE about the shown concept}? This can include anything you would want kept for sure or aspects that might drive you to buy or try it… Please type a detailed response in the space below,"Q16B. What is the most important thing you DISLIKE about the shown concept}? This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you... Please type a detailed response in the space below.","Q17. We would like to know what effect this new product might have on the other beverages you buy. If it were available, would the shown product…? \n(Concept_Replacement Product)",Q18_1 What specific product that you are currently using would the shown product replace?\n Please type in ONE specific brand or product per space provided.,Q18_2 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.,Q18_3 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.,OE_Quality_Flag,NaN
1,1.0,2024-10-11 09:41:31,2024-10-11 09:49:38,62.0,2.0,3.0,1.0,1,0,0,...,4.0,5.0,It's a classic brand.,Nothing specific to dislike.,1.0,NaN,NaN,NaN,0.0,NaN
2,2.0,2024-10-11 09:41:41,2024-10-11 09:50:42,35.0,1.0,1.0,12.0,1,1,1,...,5.0,7.0,Taste,The glass,1.0,NaN,NaN,NaN,0.0,NaN
3,9.0,2024-10-11 09:41:03,2024-10-11 09:57:26,62.0,1.0,3.0,4.0,1,0,0,...,3.0,7.0,Why?,Pure is a misnomer,1.0,NaN,NaN,NaN,1.0,NaN
4,22.0,2024-10-11 10:14:09,2024-10-11 10:22:43,64.0,1.0,1.0,11.0,1,0,0,...,3.0,4.0,I have a lot to say,Not really,2.0,NaN,Beer,Drink,1.0,NaN
5,30.0,2024-10-11 10:15:41,2024-10-11 10:55:10,57.0,2.0,1.0,4.0,1,0,0,...,5.0,7.0,I love Michelob brand and the bottle shape and...,There is nothing I dislike,1.0,NaN,NaN,NaN,0.0,NaN

In [10]:
d = {}
for i in range(len(cols)):
    if cols[i].startswith("Q"): 
        d[cols[i]] = cols[i][0:cols[i].index(' ')]
d

{'Q1. What is your current age? \n(Age)': 'Q1.',
 'Q2. What is your gender? \n(Gender)': 'Q2.',
 'Q3. Which of the following best describes the area or community in which you live? \n(Urban/Rural)': 'Q3.',
 'Q4.  Please indicate the answer that includes your entire household income in (previous year) before taxes. \n(Income)': 'Q4.',
 'Q6 Which of the following types of alcoholic beverages have you consumed in the past 4 weeks?\n(Alcohol Category)': 'Q6',
 'Q7. Which of the following beer types of have you consumed in the past 4 weeks? \n(Beer Category )': 'Q7.',
 'Q9. How relevant would you say the shown product is to you based on what you saw and read?\n(Concept Relevance)': 'Q9.',
 'Q10. How appealing or unappealing is the shown product  to you?\n(Concept Appeal)': 'Q10.',
 'Q11. How different do you think the shown product is from other beers currently available for purchase?\n(Concept Differentiation)': 'Q11.',
 'Q12. Thinking about the shown product, which option describes how believable or unbelievable you feel the description and statements made about it are?\n(Concept Beleivability)': 'Q12.',
 'Q13. How does the price fit with what you’d expect the shown to cost?\n(Concept_Price)': 'Q13.',
 'Q14. Which statement below best describes how likely you would be to buy shown product if it were available at your local stores?\n(Concept_Purchase Intent)': 'Q14.',
 'Q15. If the shwon product was available to you, how often would you expect yourself to drink at least one of these products?\n(Concept_Drinking Frequency)': 'Q15.',
 'Q16A. What is the most important thing you LIKE about the shown concept}?     This can include anything you would want kept for sure or aspects that might drive you to buy or try it…       Please type a detailed response in the space below': 'Q16A.',
 'Q16B. What is the most important thing you DISLIKE about the shown concept}?    This can include general concerns, annoyances, or any aspects of the product that need fixed for this to be more appealing to you...     Please type a detailed response in the space below.': 'Q16B.',
 'Q17. We would like to know what effect this new product might have on the other beverages you buy. If it were available, would the shown product…? \n(Concept_Replacement Product)': 'Q17.',
 'Q18_1 What specific product that you are currently using would the shown product replace?\n Please type in ONE specific brand or product per space provided.': 'Q18_1',
 'Q18_2 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.': 'Q18_2',
 'Q18_3 What specific product that you are currently using would the shown concept replace?\n Please type in ONE specific brand or product per space provided.': 'Q18_3'}

In [11]:
df = df.rename(columns = d)
df.drop(df.columns[36],axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 1 to 82
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unique ID              82 non-null     float64
 1   Start Date             82 non-null     datetime64[ns]
 2   End Date               82 non-null     datetime64[ns]
 3   Q1.                    82 non-null     float64
 4   Q2.                    82 non-null     float64
 5   Q3.                    82 non-null     float64
 6   Q4.                    82 non-null     float64
 7   Q6                     82 non-null     object
 8    Flavored/Mixed Beer   82 non-null     object
 9    Non-Alcoholic Beers   82 non-null     object
 10   Hard Ciders           82 non-null     object
 11   Hard Kombucha         82 non-null     object
 12   Wine                  82 non-null     object
 13   Hard Beverage         82 non-null     object
 14   Distilled Spirits     82 non-null     object
 15  Q7.                    82 non-null     object
 16  Domestic Regular Beer  82 non-null     object
 17  Low Calorie Carb Beer  82 non-null     object
 18  Domestic Craft         82 non-null     object
 19  Imported Mexican Beer  82 non-null     object
 20  Other Imported Beer    82 non-null     object
 21  Non-Alcoholic Beer     82 non-null     object
 22  Q9.                    82 non-null     float64
 23  Q10.                   82 non-null     float64
 24  Q11.                   82 non-null     float64
 25  Q12.                   82 non-null     float64
 26  Q13.                   82 non-null     float64
 27  Q14.                   82 non-null     float64
 28  Q15.                   82 non-null     float64
 29  Q16A.                  80 non-null     object
 30  Q16B.                  79 non-null     object
 31  Q17.                   82 non-null     float64
 32  Q18_1                  45 non-null     object
 33  Q18_2                  44 non-null     object
 34  Q18_3                  44 non-null     object
 35  OE_Quality_Flag        82 non-null     float64
dtypes: datetime64[ns](2), float64(14), object(20)
memory usage: 23.2+ KB

In [12]:
print(df["Start Date"].dt.day.value_counts())
print(df["Start Date"].dt.month.value_counts())
print(df["Start Date"].dt.year.value_counts())

Start Date
24    17
23    12
12    10
13    10
22     9
11     6
17     6
14     4
21     4
16     2
15     1
18     1
Name: count, dtype: int64
Start Date
10    82
Name: count, dtype: int64
Start Date
2024    82
Name: count, dtype: int64

In [13]:
print(df["End Date"].dt.day.value_counts())
print(df["End Date"].dt.month.value_counts())
print(df["End Date"].dt.year.value_counts())

End Date
24    17
23    12
12    10
13     9
22     9
11     6
17     6
14     5
21     4
16     2
15     1
18     1
Name: count, dtype: int64
End Date
10    82
Name: count, dtype: int64
End Date
2024    82
Name: count, dtype: int64

In [14]:
df['time_taken'] = (df['End Date'] - df['Start Date']).dt.total_seconds()

df.insert(3, 'time_taken', df.pop('time_taken'))
df.head()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q6,Flavored/Mixed Beer,...,Q13.,Q14.,Q15.,Q16A.,Q16B.,Q17.,Q18_1,Q18_2,Q18_3,OE_Quality_Flag
1,1.0,2024-10-11 09:41:31,2024-10-11 09:49:38,487.0,62.0,2.0,3.0,1.0,1,0,...,3.0,4.0,5.0,It's a classic brand.,Nothing specific to dislike.,1.0,NaN,NaN,NaN,0.0
2,2.0,2024-10-11 09:41:41,2024-10-11 09:50:42,541.0,35.0,1.0,1.0,12.0,1,1,...,3.0,5.0,7.0,Taste,The glass,1.0,NaN,NaN,NaN,0.0
3,9.0,2024-10-11 09:41:03,2024-10-11 09:57:26,983.0,62.0,1.0,3.0,4.0,1,0,...,4.0,3.0,7.0,Why?,Pure is a misnomer,1.0,NaN,NaN,NaN,1.0
4,22.0,2024-10-11 10:14:09,2024-10-11 10:22:43,514.0,64.0,1.0,1.0,11.0,1,0,...,3.0,3.0,4.0,I have a lot to say,Not really,2.0,NaN,Beer,Drink,1.0
5,30.0,2024-10-11 10:15:41,2024-10-11 10:55:10,2369.0,57.0,2.0,1.0,4.0,1,0,...,3.0,5.0,7.0,I love Michelob brand and the bottle shape and...,There is nothing I dislike,1.0,NaN,NaN,NaN,0.0

In [15]:
oe_df = pd.DataFrame()
oe_df['likes'] = df['Q16A.']
oe_df['dislikes'] = df['Q16B.']
oe_df.head()

,likes,dislikes
1,It's a classic brand.,Nothing specific to dislike.
2,Taste,The glass
3,Why?,Pure is a misnomer
4,I have a lot to say,Not really
5,I love Michelob brand and the bottle shape and...,There is nothing I dislike

In [16]:
#%pip install better_profanity

In [17]:
import re
import spacy
from better_profanity import profanity

In [18]:
# Load Spacy model for language verification
nlp = spacy.load("en_core_web_sm")

def clean_text(text):
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)  # Remove special characters
    text = text.lower().strip()  # Convert to lowercase and strip spaces
    return text

def detect_profanity(text):
    return profanity.contains_profanity(text)

def verify_language(text):
    doc = nlp(text)
    return doc.lang_ == "en"  # Check if English
"""
def preprocess_text(text):
    text = clean_text(text)
    is_profanity = detect_profanity(text)
    is_english = verify_language(text)
    
    return {"cleaned_text": text, "contains_profanity": is_profanity, "is_english": is_english}"
"""

'\ndef preprocess_text(text):\n    text = clean_text(text)\n    is_profanity = detect_profanity(text)\n    is_english = verify_language(text)\n    \n    return {"cleaned_text": text, "contains_profanity": is_profanity, "is_english": is_english}"\n'

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
from datetime import datetime
from scipy.spatial.distance import cosine

In [26]:
def calculate_entropy(text):
    if not isinstance(text, str) or len(text.strip()) == 0:
        return 0  # Return low entropy for empty text
    vectorizer = CountVectorizer()
    try:
        X = vectorizer.fit_transform([text])
    except ValueError:  # Catch empty vocabulary error
        return 0  
    probs = np.array(X.toarray()[0], dtype=np.float32)
    if np.sum(probs) == 0:
        return 0  # Avoid division by zero
    probs = probs / np.sum(probs)
    entropy = -np.sum(probs * np.log2(probs))
    return entropy


def is_gibberish(text, threshold=3.5):
    return calculate_entropy(text) < threshold

# Copy-paste detection using cosine similarity
def detect_copy_paste(response, all_responses, threshold=0.9):
    vectorizer = CountVectorizer().fit_transform([response] + all_responses)
    vectors = vectorizer.toarray()
    
    similarities = [1 - cosine(vectors[0], v) for v in vectors[1:]]
    return any(sim >= threshold for sim in similarities)

# Timestamp anomaly detection
def is_timestamp_anomalous(start_time, end_time, threshold=5):
    time_taken = (end_time - start_time).total_seconds()
    return time_taken < threshold

In [21]:
#%pip install sentence_transformers

In [22]:
"""
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("all-MiniLM-L6-v2")  # Lightweight model for semantic similarity

def check_relevance(response, expected_context):
    response_embedding = model.encode(response, convert_to_tensor=True)
    context_embedding = model.encode(expected_context, convert_to_tensor=True)
    
    similarity = util.pytorch_cos_sim(response_embedding, context_embedding).item()
    return similarity > 0.5  # Threshold for relevance"
"""

'\nfrom sentence_transformers import SentenceTransformer, util\n\nmodel = SentenceTransformer("all-MiniLM-L6-v2")  # Lightweight model for semantic similarity\n\ndef check_relevance(response, expected_context):\n    response_embedding = model.encode(response, convert_to_tensor=True)\n    context_embedding = model.encode(expected_context, convert_to_tensor=True)\n    \n    similarity = util.pytorch_cos_sim(response_embedding, context_embedding).item()\n    return similarity > 0.5  # Threshold for relevance"\n'

In [33]:
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch
# Load GPT-2 model and tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

def detect_ai_generated(text):
    # Handle empty or whitespace-only text
    if not isinstance(text, str) or text.strip() == "":
        return False  # Assume non-AI for empty input
    
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

    # Ensure input_ids is not empty
    if inputs["input_ids"].size(1) == 0:
        return False  # Cannot determine AI generation for empty inputs
    
    with torch.no_grad():  # No need for gradients
        outputs = model(**inputs, labels=inputs["input_ids"])

    loss = outputs.loss.item()  # Log probability loss
    return loss  # AI-generated text tends to have lower loss values

In [27]:
df['Q16A.'] = df['Q16A.'].fillna("")
df['Q16B.'] = df['Q16B.'].fillna("")

df['Q16A.'] = df['Q16A.'].apply(lambda x: clean_text(x))
df['Q16B.'] = df['Q16B.'].apply(lambda x: clean_text(x))

df['profanity_16A'] = df['Q16A.'].apply(lambda x: detect_profanity(x))
df['profanity_16B'] = df['Q16B.'].apply(lambda x: detect_profanity(x))

In [28]:
df['language_16A'] = df['Q16A.'].apply(lambda x: verify_language(x))
df['language_16B'] = df['Q16B.'].apply(lambda x: verify_language(x))

df['entropy_16A'] = df['Q16A.'].apply(lambda x: calculate_entropy(x))
df['entropy_16B'] = df['Q16B.'].apply(lambda x: calculate_entropy(x))

In [29]:
df.head()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q6,Flavored/Mixed Beer,...,Q18_1,Q18_2,Q18_3,OE_Quality_Flag,profanity_16A,profanity_16B,language_16A,language_16B,entropy_16A,entropy_16B
1,1.0,2024-10-11 09:41:31,2024-10-11 09:49:38,487.0,62.0,2.0,3.0,1.0,1,0,...,NaN,NaN,NaN,0.0,False,False,True,True,1.584962,2.000000
2,2.0,2024-10-11 09:41:41,2024-10-11 09:50:42,541.0,35.0,1.0,1.0,12.0,1,1,...,NaN,NaN,NaN,0.0,False,False,True,True,-0.000000,1.000000
3,9.0,2024-10-11 09:41:03,2024-10-11 09:57:26,983.0,62.0,1.0,3.0,4.0,1,0,...,NaN,NaN,NaN,1.0,False,False,True,True,-0.000000,1.584962
4,22.0,2024-10-11 10:14:09,2024-10-11 10:22:43,514.0,64.0,1.0,1.0,11.0,1,0,...,NaN,Beer,Drink,1.0,False,False,True,True,2.000000,1.000000
5,30.0,2024-10-11 10:15:41,2024-10-11 10:55:10,2369.0,57.0,2.0,1.0,4.0,1,0,...,NaN,NaN,NaN,0.0,False,False,True,True,3.418296,2.000000

In [30]:
df.describe()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q9.,Q10.,Q11.,Q12.,Q13.,Q14.,Q15.,Q17.,OE_Quality_Flag,entropy_16A,entropy_16B
count,82.000000,82,82,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000
mean,1586.609756,2024-10-18 22:10:26.865853696,2024-10-18 22:24:55.926829056,869.060976,44.646341,1.390244,2.524390,7.085366,3.646341,3.804878,3.414634,3.134146,3.158537,3.731707,4.963415,1.707317,0.207317,1.911340,1.473398
min,1.000000,2024-10-11 09:41:03,2024-10-11 09:49:38,240.000000,24.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,-0.000000,-0.000000
25%,301.500000,2024-10-13 12:21:26.249999872,2024-10-13 12:36:37,542.500000,33.000000,1.000000,1.000000,4.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,1.000000,0.000000,1.000000,0.000000
50%,1965.000000,2024-10-21 18:51:43.500000,2024-10-21 19:20:49.500000,721.000000,45.000000,1.000000,3.000000,7.000000,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,6.000000,2.000000,0.000000,2.000000,1.584962
75%,2659.500000,2024-10-23 17:09:01.750000128,2024-10-23 17:24:59.249999872,1002.500000,56.500000,2.000000,3.000000,11.000000,4.750000,5.000000,4.000000,4.000000,3.750000,5.000000,7.000000,2.000000,0.000000,2.584963,2.584963
max,3216.000000,2024-10-24 18:04:07,2024-10-24 18:15:59,2764.000000,65.000000,2.000000,5.000000,12.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,8.000000,3.000000,1.000000,4.523563,4.969816
std,1173.048806,NaN,NaN,522.862665,12.759283,0.490807,1.307392,3.545824,1.200534,1.047502,1.196200,0.715994,0.761245,1.277041,2.327745,0.693672,0.407879,1.115590,1.264464

In [34]:
df['ai_generated_16A'] = df['Q16A.'].apply(lambda x: detect_ai_generated(x))
df['ai_generated_16B'] = df['Q16B.'].apply(lambda x: detect_ai_generated(x))

In [35]:
df.head()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q6,Flavored/Mixed Beer,...,Q18_3,OE_Quality_Flag,profanity_16A,profanity_16B,language_16A,language_16B,entropy_16A,entropy_16B,ai_generated_16A,ai_generated_16B
1,1.0,2024-10-11 09:41:31,2024-10-11 09:49:38,487.0,62.0,2.0,3.0,1.0,1,0,...,NaN,0.0,False,False,True,True,1.584962,2.000000,6.47398,7.591885
2,2.0,2024-10-11 09:41:41,2024-10-11 09:50:42,541.0,35.0,1.0,1.0,12.0,1,1,...,NaN,0.0,False,False,True,True,-0.000000,1.000000,10.35298,9.65913
3,9.0,2024-10-11 09:41:03,2024-10-11 09:57:26,983.0,62.0,1.0,3.0,4.0,1,0,...,NaN,1.0,False,False,True,True,-0.000000,1.584962,NaN,2.968733
4,22.0,2024-10-11 10:14:09,2024-10-11 10:22:43,514.0,64.0,1.0,1.0,11.0,1,0,...,Drink,1.0,False,False,True,True,2.000000,1.000000,3.06724,6.870985
5,30.0,2024-10-11 10:15:41,2024-10-11 10:55:10,2369.0,57.0,2.0,1.0,4.0,1,0,...,NaN,0.0,False,False,True,True,3.418296,2.000000,6.503458,5.484946

In [36]:
df.describe()

,Unique ID,Start Date,End Date,time_taken,Q1.,Q2.,Q3.,Q4.,Q9.,Q10.,Q11.,Q12.,Q13.,Q14.,Q15.,Q17.,OE_Quality_Flag,entropy_16A,entropy_16B
count,82.000000,82,82,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000
mean,1586.609756,2024-10-18 22:10:26.865853696,2024-10-18 22:24:55.926829056,869.060976,44.646341,1.390244,2.524390,7.085366,3.646341,3.804878,3.414634,3.134146,3.158537,3.731707,4.963415,1.707317,0.207317,1.911340,1.473398
min,1.000000,2024-10-11 09:41:03,2024-10-11 09:49:38,240.000000,24.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,-0.000000,-0.000000
25%,301.500000,2024-10-13 12:21:26.249999872,2024-10-13 12:36:37,542.500000,33.000000,1.000000,1.000000,4.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,1.000000,0.000000,1.000000,0.000000
50%,1965.000000,2024-10-21 18:51:43.500000,2024-10-21 19:20:49.500000,721.000000,45.000000,1.000000,3.000000,7.000000,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,6.000000,2.000000,0.000000,2.000000,1.584962
75%,2659.500000,2024-10-23 17:09:01.750000128,2024-10-23 17:24:59.249999872,1002.500000,56.500000,2.000000,3.000000,11.000000,4.750000,5.000000,4.000000,4.000000,3.750000,5.000000,7.000000,2.000000,0.000000,2.584963,2.584963
max,3216.000000,2024-10-24 18:04:07,2024-10-24 18:15:59,2764.000000,65.000000,2.000000,5.000000,12.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,8.000000,3.000000,1.000000,4.523563,4.969816
std,1173.048806,NaN,NaN,522.862665,12.759283,0.490807,1.307392,3.545824,1.200534,1.047502,1.196200,0.715994,0.761245,1.277041,2.327745,0.693672,0.407879,1.115590,1.264464